on: 
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to build'     
        required: true
        type: choice
        options:
        - docker
env:
  FILE_PATH: ${{ github.event.inputs.image }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets. DOCKER_PASSWORD }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    
    - name: Build and push docker image to DockerHub
      id: build-image
      run: | 
        cd $FILE_PATH
        VERSION_READABLE=$(git describe --tag)
        docker build --platform "linux/amd64" -t nehagarg/docker-image:$VERSION_READABLE .
        echo "::set-output name=IMAGE::nehagarg/docker-image:$VERSION_READABLE"

    - uses: trstringer/manual-approval@v1
      with:
          secret: ${{ github.TOKEN }}
          approvers: techslaves
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: '${{ steps.build-image.outputs.IMAGE }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          output: ${{ steps.date.outputs.date }}
          severity: 'CRITICAL,HIGH'
